/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    Avatar: typeof import('./src/components/avatar.vue')['default']
    ChatCard: typeof import('./src/components/chatCard.vue')['default']
    ContactCard: typeof import('./src/components/contactCard.vue')['default']
    Mmc: typeof import('./src/components/mmc.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopSearch: typeof import('./src/components/topSearch.vue')['default']
  }
}
